### Criar uma coleção para teste
# @name criarColecao
POST http://localhost:3000/colecoes
Content-Type: application/json

{
    "nome": "Destaques"
}

### Listar todos os produtos
GET http://localhost:3000/produtos
Accept: application/json

### Listar produtos por coleção
# @name listarProdutosPorColecao
GET http://localhost:3000/produtos?colecaoId=bce35373-42ef-464d-8fe7-7219f45d534f
Accept: application/json

### Buscar produto por ID
GET http://localhost:3000/produtos/47cf30ba-6c18-4497-bad2-e653c238eaa2
Accept: application/json

### Criar novo produto
POST http://localhost:3000/produtos
Content-Type: application/json
Accept: application/json

{
  "nome": "Adidas v12",
  "marca": "Adidas",
  "tamanhos": [40],
  "preco": 799.90,
  "imagens": [
    {
      "url": "https://example.com/air-force-1.jpg",
      "descricao": "Nike Air Force 1 - Vista frontal",
      "principal": true
    }
  ],
  "colecaoIds": ["e9046bca-68d9-43be-94f9-4dea025ff558"]
}

### Editar um produto
PUT http://localhost:3000/produtos/cc29b6e8-1dd7-4553-b93e-8bab6119d678
Content-Type: application/json

{
  "nome": "Nike Air Max Atualizado",
  "marca": "Nike",
  "preco": 59.90,
  "tamanhos": [38, 39, 40, 41, 42],
  "imagens": [
    {
      "url": "https://example.com/nike-air-max-1.jpg",
      "descricao": "Vista frontal",
      "principal": true
    },
    {
      "url": "https://example.com/nike-air-max-2.jpg",
      "descricao": "Vista lateral",
      "principal": false
    }
  ],
  "colecaoIds": []
}

### Remover produto
DELETE http://localhost:3000/produtos/7ed8d307-8628-49fa-8d7e-9b33385edbaa

### Listar produtos paginado
GET http://localhost:3000/produtos?page=1&pageSize=12&
Accept: application/json

### Listar produtos paginado por colecao
GET http://localhost:3000/produtos?page=1&pageSize=12&colecaoId=bce35373-42ef-464d-8fe7-7219f45d534f
Accept: application/json

### Listar produtos por múltiplas marcas
GET http://localhost:3000/produtos?marca=Nike&marca=Adidas&page=1&pageSize=12
Accept: application/json

### Listar produtos por slug da coleção
# @name listarProdutosPorColecaoSlug
GET http://localhost:3000/produtos?colecaoSlug=destaques&page=1&pageSize=12
Accept: application/json
